# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: prod-deploy
on: 
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into instance
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIV_KEY }}
          username: ubuntu
          host: ${{ secrets.HOST }} # server host
          #passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            npm ci
            npm run test
            echo 'chnageed dir'
            cd /home/ubuntu/gitAction-demo
            echo 'checkout branch'
            sudo git checkout main
            echo ${{ secrets.DOT_ENV }} base64 -d >> .env
            echo 'pull origin main'
            sudo git pull origin main
            echo 'npm clean and install'
            sudo npm ci
            
            
