# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: prod-deploy
on: 
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into instance
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIV_KEY }}
          username: ubuntu
          host: ${{ secrets.HOST }} # server host
          script: |
            set -e
            cd /home/ubuntu/gitAction-demo
            echo 'Checkout branch'
            git checkout main
            # Checkout package lock file
            git checkout package-lock.json
            # Pull latest code
            echo 'Pulling latest code from branch'
            sudo git pull origin main
            # Install dependencies if any
            echo 'Installing dependencies'
            npm i
            # start server
            npm start
