name: Slack Notifications

on:
  pull_request:
    branches: [ main ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_SECRET }}
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C02Q7DJKA3A\",\"text\": \"helllo aditya\"}'
